<a href="https://colab.research.google.com/github/yashgeed-AI-DS/Pandas/blob/main/Pandas_Class5_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Class 5 Assignment

## Topics
- sort_values()
- mean()
- median()
- mode()
- value_counts()
- corr()
- cov()

Difficulty: Easy to Moderate

## Q1. Sort Age in Ascending Order

Input:
Age = [25, 18, 30, 22]

Output:
18
22
25
30

In [2]:
import pandas as pd
data = pd.DataFrame({
    'Name':['John','Robert','Harry','Steve'],
    'Age':[25,18,30,22],
    'Marks':[70,95,80,60],
})
print(data)
data.sort_values(by='Age')

     Name  Age  Marks
0    John   25     70
1  Robert   18     95
2   Harry   30     80
3   Steve   22     60

     Name  Age  Marks
1  Robert   18     95
3   Steve   22     60
0    John   25     70
2   Harry   30     80

## Q2. Sort Marks in Descending Order

Input:
Marks = [70, 95, 80, 60]

Output:
95
80
70
60

In [8]:
print(data.sort_values(by = 'Marks', ascending = False))

     Name  Age  Marks
1  Robert   18     95
2   Harry   30     80
0    John   25     70
3   Steve   22     60

## Q3. Find Mean Age

Input:
Age = [20, 25, 30, 25]

Output:
25.0

In [10]:
data.mean( numeric_only = True)

Age      23.75
Marks    76.25
dtype: float64

## Q4. Find Median Marks

Input:
Marks = [50, 60, 70, 80, 90]

Output:
70

In [11]:
data.median(numeric_only = True)

Age      23.5
Marks    75.0
dtype: float64

## Q5. Find Mode

Input:
Age = [20, 25, 25, 30, 25]

Output:
25

In [12]:
data.mode()

     Name  Age  Marks
0   Harry   18     60
1    John   22     70
2  Robert   25     80
3   Steve   30     95

## Q6. Find Maximum Score

Input:
Score = [78, 90, 67, 88]

Output:
90

In [34]:
data = pd.DataFrame({
    'Marks':[78,90,67,88]
})
print(data)
print(data.max(numeric_only = True))

   Marks
0     78
1     90
2     67
3     88
Marks    90
dtype: int64

## Q7. Find Minimum Score

Input:
Score = [78, 90, 67, 88]

Output:
67

In [33]:
data = pd.DataFrame({
    'Marks':[78,90,67,88]
})
print(data)
print(data.min(numeric_only = True))

   Marks
0     78
1     90
2     67
3     88
Marks    67
dtype: int64

## Q8. Count City Frequency

Input:
City = ['Bhopal','Indore','Bhopal','Jabalpur']

Output:
Bhopal      2
Indore      1
Jabalpur    1

In [35]:
data = pd.DataFrame({
    'City':['Bhopal','Indore','Bhopal','Jabalpur']
})
print(data)
print(data['City'].value_counts())

       City
0    Bhopal
1    Indore
2    Bhopal
3  Jabalpur
City
Bhopal      2
Indore      1
Jabalpur    1
Name: count, dtype: int64

## Q9. Find Percentage Frequency

Input:
City = ['A','A','B','C']

Output:
A = 50%
B = 25%
C = 25%

In [39]:
data = pd.DataFrame({
    'City':['A','A','B','C']
})
print(data)
print(data['City'].value_counts(normalize = True)*100)

  City
0    A
1    A
2    B
3    C
City
A    50.0
B    25.0
C    25.0
Name: proportion, dtype: float64

## Q10. Sort DataFrame by Salary

Input:
Name   Salary
Aman   30000
Raj    50000
Riya   40000

Output:
Raj
Riya
Aman

In [36]:
data = pd.DataFrame({
    'Name':['Aman','Raj','Riya'],
    'Salary':[30000,50000,40000]
})
print(data)
print(data.sort_values(by = 'Salary'))

   Name  Salary
0  Aman   30000
1   Raj   50000
2  Riya   40000
   Name  Salary
0  Aman   30000
2  Riya   40000
1   Raj   50000

## Q11. Find Correlation

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
1.0

In [32]:
data = pd.DataFrame({
    'Math':[10,20,30,40],
    'Science':[15,25,35,45]
})
print(data)
print(data.corr())

   Math  Science
0    10       15
1    20       25
2    30       35
3    40       45
         Math  Science
Math      1.0      1.0
Science   1.0      1.0

## Q12. Find Covariance

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
166.67 (approx)

In [31]:
data = pd.DataFrame({
    'Math':[10,20,30,40],
    'Science':[15,25,35,45]
})
print(data)
print(data.cov())

   Math  Science
0    10       15
1    20       25
2    30       35
3    40       45
               Math     Science
Math     166.666667  166.666667
Science  166.666667  166.666667

## Q13. Sort by Two Columns

Input:
Sort by City and then Age

Output:
Sorted DataFrame

In [29]:
data = pd.DataFrame({
    'City':['Bhopal','Indore','Bhopal','Jabalpur'],
    'Age':[20,25,25,30],
})
print(data)
print(data.sort_values(by = ['City','Age']))

       City  Age
0    Bhopal   20
1    Indore   25
2    Bhopal   25
3  Jabalpur   30
       City  Age
0    Bhopal   20
2    Bhopal   25
1    Indore   25
3  Jabalpur   30

## Q14. Student Statistics

Input:
Marks = [60,70,80,90]

Output:
Mean = 75
Median = 75
Max = 90
Min = 60

In [27]:
data = pd.DataFrame({
    'Marks':[60,70,80,90],
})
print(data)
print(data.mean(numeric_only = True))
print(data.median(numeric_only = True))
print(data.max(numeric_only = True))
print(data.min(numeric_only = True))

   Marks
0     60
1     70
2     80
3     90
Marks    75.0
dtype: float64
Marks    75.0
dtype: float64
Marks    90
dtype: int64
Marks    60
dtype: int64

## Q15. Mini Practice

Create a DataFrame with:
Name, Age, Score, Height

Tasks:
1. Sort by Score (Descending)
2. Find Mean Age
3. Find Median Height
4. Show Score Frequency

In [22]:
data = pd.DataFrame({
    'Name':['John','Robert','Harry','Steve'],
    'Age':[25,18,30,22],
    'Score':[70,95,80,60],
    'Height':[170,165,175,180]
})
print(data)
print(data.sort_values(by = 'Score',ascending = False))
print(data['Age'].mean())
print(data['Height'].median())
print(data ['Score'].value_counts())

     Name  Age  Score  Height
0    John   25     70     170
1  Robert   18     95     165
2   Harry   30     80     175
3   Steve   22     60     180
     Name  Age  Score  Height
1  Robert   18     95     165
2   Harry   30     80     175
0    John   25     70     170
3   Steve   22     60     180
23.75
172.5
Score
70    1
95    1
80    1
60    1
Name: count, dtype: int64